name: ict_family_demo
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.0+1
  image_picker: ^0.6.2+3
  firebase_storage: ^3.1.1
  firebase_auth: ^0.15.3
  google_sign_in: ^4.1.1
  geolocator: ^5.1.5
  uuid: ^2.0.4
  image: ^2.1.4
  animator: ^1.0.0+3
  cupertino_icons: ^0.1.2
  path_provider: ^1.5.1
  firebase_messaging: ^6.0.9
  timeago: ^2.0.24
  cached_network_image: ^2.0.0
  flutter_svg: ^0.15.0
  curved_navigation_bar: ^0.3.1
  flutter_form_builder: ^3.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
  assets:
    - assets/images/search.svg
    - assets/images/upload.svg
    - assets/images/no_content.svg
    - assets/images/activity_feed.svg
    - assets/images/google_signin_button.png
